
--코멘트 찾기 
SELECT *
FROM T_POLYGLOT_MST A
LEFT OUTER JOIN T_POLYGLOT_DTL B
ON A.ITEM_CD = B.ITEM_CD
WHERE 1=1;


SELECT * FROM T_POLYGLOT_MST;
SELECT * FROM T_POLYGLOT_DTL;
SELECT * FROM T_POLYGLOT_DTL 
    WHERE trnf_nm like '사번';